server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/some_database}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:password}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  server:
    port: 8080

logging:
  level:
    root: info
    edu.vgtu.project: debug
    org.springframework: warn