# Данные подключения к БД
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/worker_qualification
    username: postgres
    password: zaq1@WSX
server:
  port: 8090