server:
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger.html

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/some_database}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:password}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  server:
    port: 8090
  mail:
    host: smtp.mail.ru
    port: 465
    username: ${MAIL_USER_EMAIL:nikita-saprygin@mail.ru}
    password: ${MAIL_USER_PASSWORD:pTq4fKvZtVd1e2FF05RR}
    protocol: smtp
    properties:
     mail.transport.protocol: smtp
     mail.smtp.auth: true
     mail.smtp.ssl.enable: true
     mail.smtp.starttls.enable: true

logging:
  level:
    root: info
    edu.vgtu.project: debug
    org.springframework: warn

notification:
  thread-pool: ${THREAD_POOL_SIZE:10}
  recipient: ${RECIPIENT:nikita-saprygin@mail.ru}