spring:
  jpa:
    show-sql: true
    properties.hibernate.default_schema: service
  datasource:
    url: jdbc:postgresql://localhost:6542/project
    username: worker-qualification-service
    password: secret
    schema: service
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:6542/project
    user: worker-qualification-service
    password: secret
    schemas: service
    validateMigrationNaming: true
  mail:
    host: smtp.mail.ru
    port: 465
    username: nikita-saprygin@mail.ru
    password: pTq4fKvZtVd1e2FF05RR
server:
  port: 8080

notification:
  thread-pool: 10
  recipient: pwgda30a@gmail.com

logging:
  org.hibernate: debug
